### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Sxlitude** [archaeopteryx1/quickmongo#52]
can you add a `list` method? 

### what is it?
it's a method which will return all existing keys starting from a prefix

### example?
suppose I have these keys: `user_1`, `user_2`, `user_3`

```js
db.list("user_").then((keys) => {
  console.log(keys); // 'user_1', 'user_2', 'user_3'
})
```

**Comment by WoozyDev** [comment]
```js
db.all({
    filter: (user) => user.ID.startsWith('user_')
}).then((users) => {
    console.log(users); // [{ ID: "user_1", data: "some data" }, { ID: "user_2", data: "some data" }, { ID: "user_3", data: "some data" }]
});
```

**Comment by archaeopteryx1** [comment]
> can you add a `list` method?
> 
> ### what is it?
> it's a method which will return all existing keys starting from a prefix
> 
> ### example?
> suppose I have these keys: `user_1`, `user_2`, `user_3`
> 
> ```js
> db.list("user_").then((keys) => {
>   console.log(keys); // 'user_1', 'user_2', 'user_3'
> })
> ```

I forgot to mention this but with [v5.2.0](https://github.com/archaeopteryx1/quickmongo/releases/tag/v5.2.0) update, there's a `startsWith` method in quickmongo instance. You can match your keys like this:

```js
const keys = (await db.startsWith("user_")).map(m => m.ID);
```
